spring.application.name=TechSupport


spring.datasource.url=jdbc:postgresql://localhost/TechSupport
spring.datasource.username=postgres
spring.datasource.password=Sen@c2023
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.expiracao =5
spring.secret ="auvblavnb"
spring.emissor = "alunovitor"