import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

// Geist / Geist_Mono: fontes do Google Fonts que o Next.js baixa e otimiza em tempo de
// build. A "variable" gera uma variável CSS (--font-geist-sans) usada lá no globals.css.
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// metadata: objeto especial que o Next.js lê sozinho e usa pra gerar automaticamente
// as tags <title> e <meta name="description"> dentro do <head> do HTML.
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// RootLayout = o layout RAIZ do projeto. Todas as rotas (login, home, usuarios, etc.)
// passam por aqui, porque ele é o layout.tsx mais externo dentro da pasta app/.
// Ele nunca é "desligado" ou "trocado" por um layout mais interno (ex: o do (sistema)) —
// os layouts internos só se aninham por DENTRO dele, nunca o substituem.
// {children} é onde o Next.js injeta o conteúdo da rota que está sendo acessada no momento.
export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="pt-BR"
      className="h-full">
      <body>{children}</body>
    </html>
  );
}
